spring.application.name=coworking-technical-test

spring.datasource.url=jdbc:mysql://localhost:3306/coworking?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Bogota
spring.datasource.username=root
spring.datasource.password=1234

spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true

spring.jpa.hibernate.ddl-auto=update
spring.error.include-message=always
spring.sql.init.mode=always
